// <auto-generated />
using System;
using EscolaCleanArch.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EscolaCleanArch.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210610110226_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EscolaCleanArch.Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("AlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RA")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("AlunoId");

                    b.HasIndex("CursoId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            CursoId = 3,
                            Nome = "Eduardo Alves Canuto",
                            Periodo = "Manhã",
                            RA = "00001"
                        },
                        new
                        {
                            AlunoId = 2,
                            CursoId = 2,
                            Nome = "Viviane Fidelis do Nascimento",
                            Periodo = "Tarde",
                            RA = "00002"
                        },
                        new
                        {
                            AlunoId = 3,
                            CursoId = 1,
                            Nome = "Thiago Fidelis Alves Canuto",
                            Periodo = "Noite",
                            RA = "00003"
                        });
                });

            modelBuilder.Entity("EscolaCleanArch.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = 1,
                            Nome = "Ensino Fundamental"
                        },
                        new
                        {
                            CursoId = 2,
                            Nome = "Ensino Médio"
                        },
                        new
                        {
                            CursoId = 3,
                            Nome = "Faculdade"
                        },
                        new
                        {
                            CursoId = 4,
                            Nome = "Pós-Graduação"
                        });
                });

            modelBuilder.Entity("EscolaCleanArch.Domain.Entities.Diciplina", b =>
                {
                    b.Property<int>("DiciplinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("NotaMinima")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("DiciplinaId");

                    b.HasIndex("CursoId");

                    b.ToTable("Diciplinas");

                    b.HasData(
                        new
                        {
                            DiciplinaId = 1,
                            Nome = "Portugês Ensino Fundamental",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 2,
                            Nome = "Matemática Ensino Fundamental",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 3,
                            Nome = "Ciências Ensino Fundamental",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 4,
                            Nome = "Histógia Ensino Fundamental",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 5,
                            Nome = "Geográfia Ensino Fundamental",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 6,
                            Nome = "Portugês Ensino Médio",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 7,
                            Nome = "Matemática Ensino Médio",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 8,
                            Nome = "Fisíca Ensino Médio",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 9,
                            Nome = "Histógia Ensino Médio",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 10,
                            Nome = "Geográfia Ensino Médio",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 11,
                            Nome = "Portugês Faculdade",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 12,
                            Nome = "Matemática Faculdade",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 13,
                            Nome = "Fisíca Faculdade",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 14,
                            Nome = "Histógia Faculdade",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 15,
                            Nome = "Geográfia Faculdade",
                            NotaMinima = 7.0m
                        });
                });

            modelBuilder.Entity("EscolaCleanArch.Domain.Entities.NotasAluno", b =>
                {
                    b.Property<int>("NotaAlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int?>("CursoId")
                        .HasColumnType("int");

                    b.Property<int?>("DiciplinaId")
                        .HasColumnType("int");

                    b.Property<decimal>("NotaDiciplina")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("NotaAlunoId");

                    b.HasIndex("AlunoId");

                    b.HasIndex("CursoId");

                    b.HasIndex("DiciplinaId");

                    b.ToTable("NotasAlunos");
                });

            modelBuilder.Entity("EscolaCleanArch.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("EscolaCleanArch.Domain.Entities.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("EscolaCleanArch.Domain.Entities.Diciplina", b =>
                {
                    b.HasOne("EscolaCleanArch.Domain.Entities.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("EscolaCleanArch.Domain.Entities.NotasAluno", b =>
                {
                    b.HasOne("EscolaCleanArch.Domain.Entities.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId");

                    b.HasOne("EscolaCleanArch.Domain.Entities.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId");

                    b.HasOne("EscolaCleanArch.Domain.Entities.Diciplina", "Diciplina")
                        .WithMany()
                        .HasForeignKey("DiciplinaId");

                    b.Navigation("Aluno");

                    b.Navigation("Curso");

                    b.Navigation("Diciplina");
                });
#pragma warning restore 612, 618
        }
    }
}
