// <auto-generated />
using System;
using EscolaCleanArch.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EscolaCleanArch.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210608103829_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EscolaCleanArch.Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("AlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CursoId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RA")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("AlunoId");

                    b.HasIndex("CursoId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            Nome = "Eduardo Alves Canuto",
                            Periodo = "Manhã",
                            RA = "00001"
                        },
                        new
                        {
                            AlunoId = 2,
                            Nome = "Viviane Fidelis do Nascimento",
                            Periodo = "Tarde",
                            RA = "00002"
                        },
                        new
                        {
                            AlunoId = 3,
                            Nome = "Thiago Fidelis Alves Canuto",
                            Periodo = "Noite",
                            RA = "00003"
                        });
                });

            modelBuilder.Entity("EscolaCleanArch.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = 1,
                            Nome = "Ensino Fundamental"
                        },
                        new
                        {
                            CursoId = 2,
                            Nome = "Ensino Médio"
                        });
                });

            modelBuilder.Entity("EscolaCleanArch.Domain.Entities.Diciplina", b =>
                {
                    b.Property<int>("DiciplinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("NotaMinima")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("DiciplinaId");

                    b.HasIndex("CursoId");

                    b.ToTable("Diciplinas");

                    b.HasData(
                        new
                        {
                            DiciplinaId = 1,
                            Nome = "Portugês",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 2,
                            Nome = "Matemática",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 3,
                            Nome = "Ciências",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 4,
                            Nome = "Histógia",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 5,
                            Nome = "Geográfia",
                            NotaMinima = 7.0m
                        });
                });

            modelBuilder.Entity("EscolaCleanArch.Domain.Entities.NotasAluno", b =>
                {
                    b.Property<int>("NotaAlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int?>("CursoId")
                        .HasColumnType("int");

                    b.Property<int?>("DiciplinaId")
                        .HasColumnType("int");

                    b.Property<decimal>("NotaDiciplina")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("NotaAlunoId");

                    b.HasIndex("AlunoId");

                    b.HasIndex("CursoId");

                    b.HasIndex("DiciplinaId");

                    b.ToTable("NotasAlunos");
                });

            modelBuilder.Entity("EscolaCleanArch.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("EscolaCleanArch.Domain.Entities.Curso", "Curso")
                        .WithMany("AlunosCurso")
                        .HasForeignKey("CursoId");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("EscolaCleanArch.Domain.Entities.Diciplina", b =>
                {
                    b.HasOne("EscolaCleanArch.Domain.Entities.Curso", null)
                        .WithMany("DiciplinasCurso")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("EscolaCleanArch.Domain.Entities.NotasAluno", b =>
                {
                    b.HasOne("EscolaCleanArch.Domain.Entities.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId");

                    b.HasOne("EscolaCleanArch.Domain.Entities.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId");

                    b.HasOne("EscolaCleanArch.Domain.Entities.Diciplina", "Diciplina")
                        .WithMany()
                        .HasForeignKey("DiciplinaId");

                    b.Navigation("Aluno");

                    b.Navigation("Curso");

                    b.Navigation("Diciplina");
                });

            modelBuilder.Entity("EscolaCleanArch.Domain.Entities.Curso", b =>
                {
                    b.Navigation("AlunosCurso");

                    b.Navigation("DiciplinasCurso");
                });
#pragma warning restore 612, 618
        }
    }
}
