// <auto-generated />
using EscolaCleanArch.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EscolaCleanArch.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210606184420_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EscolaCleanArch.Domain.Entities.Diciplina", b =>
                {
                    b.Property<int>("DiciplinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("NotaMinima")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("DiciplinaId");

                    b.ToTable("Diciplinas");

                    b.HasData(
                        new
                        {
                            DiciplinaId = 1,
                            Nome = "Portugês",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 2,
                            Nome = "Matemática",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 3,
                            Nome = "Ciências",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 4,
                            Nome = "Histógia",
                            NotaMinima = 7.0m
                        },
                        new
                        {
                            DiciplinaId = 5,
                            Nome = "Geográfia",
                            NotaMinima = 7.0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
